/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobId = IDL.Nat32;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Reference = IDL.Record({
  'contactInfo' : IDL.Text,
  'relationship' : IDL.Text,
  'fullName' : IDL.Text,
});
export const EducationEntry = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'institution' : IDL.Text,
  'description' : IDL.Text,
  'degree' : IDL.Text,
  'fieldOfStudy' : IDL.Text,
  'startDate' : Time,
});
export const ExperienceEntry = IDL.Record({
  'title' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'company' : IDL.Text,
  'location' : IDL.Text,
  'startDate' : Time,
});
export const Certification = IDL.Record({
  'issueDate' : Time,
  'name' : IDL.Text,
  'expirationDate' : IDL.Opt(Time),
  'issuingOrganization' : IDL.Text,
  'credentialId' : IDL.Text,
  'credentialUrl' : IDL.Text,
});
export const JobType = IDL.Variant({
  'internship' : IDL.Null,
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
  'freelance' : IDL.Null,
});
export const Availability = IDL.Record({
  'preferredStartDate' : IDL.Opt(Time),
  'isAvailable' : IDL.Bool,
  'weeklyHours' : IDL.Opt(IDL.Nat),
});
export const CandidateProfile = IDL.Record({
  'references' : IDL.Vec(IDL.Text),
  'preferredJobTypes' : IDL.Vec(JobType),
  'userId' : IDL.Principal,
  'headline' : IDL.Text,
  'hourlyRate' : IDL.Opt(IDL.Nat),
  'education' : IDL.Vec(EducationEntry),
  'email' : IDL.Text,
  'experience' : IDL.Vec(ExperienceEntry),
  'availability' : Availability,
  'summary' : IDL.Text,
  'portfolioLinks' : IDL.Vec(IDL.Text),
  'certifications' : IDL.Vec(Certification),
  'lastName' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'resumeUrl' : IDL.Opt(IDL.Text),
  'firstName' : IDL.Text,
});
export const CompiledCV = IDL.Record({
  'references' : IDL.Vec(Reference),
  'education' : IDL.Vec(EducationEntry),
  'summary' : IDL.Text,
  'experiences' : IDL.Vec(ExperienceEntry),
  'certifications' : IDL.Vec(Certification),
  'personalInfo' : CandidateProfile,
  'skills' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const FilterCriteria = IDL.Record({
  'experienceLevel' : IDL.Text,
  'employmentType' : IDL.Text,
  'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'skills' : IDL.Vec(IDL.Text),
  'educationLevel' : IDL.Text,
  'location' : IDL.Text,
});
export const JobPosting = IDL.Record({
  'id' : JobId,
  'applicationDeadline' : Time,
  'experienceLevel' : IDL.Text,
  'title' : IDL.Text,
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'employmentType' : IDL.Text,
  'company' : IDL.Text,
  'employerId' : IDL.Principal,
  'benefits' : IDL.Vec(IDL.Text),
  'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'educationLevel' : IDL.Text,
  'location' : IDL.Text,
});
export const Application = IDL.Record({
  'status' : IDL.Text,
  'resume' : IDL.Opt(IDL.Text),
  'appliedAt' : Time,
  'applicantId' : IDL.Principal,
  'expectedSalary' : IDL.Opt(IDL.Nat),
  'jobId' : IDL.Nat32,
  'coverLetter' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func(
      [JobId, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJobPosting' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        Time,
      ],
      [JobId],
      [],
    ),
  'cvFind' : IDL.Func([], [CompiledCV], ['query']),
  'deleteJobPosting' : IDL.Func([JobId], [], []),
  'filterCandidates' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Vec(CandidateProfile)],
      ['query'],
    ),
  'getCallerCandidateProfile' : IDL.Func(
      [],
      [IDL.Opt(CandidateProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CandidateProfile)],
      ['query'],
    ),
  'getFilteredJobPostings' : IDL.Func(
      [FilterCriteria],
      [IDL.Vec(JobPosting)],
      ['query'],
    ),
  'getJobApplications' : IDL.Func([JobId], [IDL.Vec(Application)], ['query']),
  'getJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getUserApplications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCandidateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(ExperienceEntry),
        IDL.Vec(EducationEntry),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Nat),
        Availability,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(Certification),
        IDL.Vec(JobType),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateApplicationStatus' : IDL.Func(
      [JobId, IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'updateJobPosting' : IDL.Func(
      [
        JobId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        Time,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobId = IDL.Nat32;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Reference = IDL.Record({
    'contactInfo' : IDL.Text,
    'relationship' : IDL.Text,
    'fullName' : IDL.Text,
  });
  const EducationEntry = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'institution' : IDL.Text,
    'description' : IDL.Text,
    'degree' : IDL.Text,
    'fieldOfStudy' : IDL.Text,
    'startDate' : Time,
  });
  const ExperienceEntry = IDL.Record({
    'title' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'company' : IDL.Text,
    'location' : IDL.Text,
    'startDate' : Time,
  });
  const Certification = IDL.Record({
    'issueDate' : Time,
    'name' : IDL.Text,
    'expirationDate' : IDL.Opt(Time),
    'issuingOrganization' : IDL.Text,
    'credentialId' : IDL.Text,
    'credentialUrl' : IDL.Text,
  });
  const JobType = IDL.Variant({
    'internship' : IDL.Null,
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
    'freelance' : IDL.Null,
  });
  const Availability = IDL.Record({
    'preferredStartDate' : IDL.Opt(Time),
    'isAvailable' : IDL.Bool,
    'weeklyHours' : IDL.Opt(IDL.Nat),
  });
  const CandidateProfile = IDL.Record({
    'references' : IDL.Vec(IDL.Text),
    'preferredJobTypes' : IDL.Vec(JobType),
    'userId' : IDL.Principal,
    'headline' : IDL.Text,
    'hourlyRate' : IDL.Opt(IDL.Nat),
    'education' : IDL.Vec(EducationEntry),
    'email' : IDL.Text,
    'experience' : IDL.Vec(ExperienceEntry),
    'availability' : Availability,
    'summary' : IDL.Text,
    'portfolioLinks' : IDL.Vec(IDL.Text),
    'certifications' : IDL.Vec(Certification),
    'lastName' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'resumeUrl' : IDL.Opt(IDL.Text),
    'firstName' : IDL.Text,
  });
  const CompiledCV = IDL.Record({
    'references' : IDL.Vec(Reference),
    'education' : IDL.Vec(EducationEntry),
    'summary' : IDL.Text,
    'experiences' : IDL.Vec(ExperienceEntry),
    'certifications' : IDL.Vec(Certification),
    'personalInfo' : CandidateProfile,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const FilterCriteria = IDL.Record({
    'experienceLevel' : IDL.Text,
    'employmentType' : IDL.Text,
    'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'skills' : IDL.Vec(IDL.Text),
    'educationLevel' : IDL.Text,
    'location' : IDL.Text,
  });
  const JobPosting = IDL.Record({
    'id' : JobId,
    'applicationDeadline' : Time,
    'experienceLevel' : IDL.Text,
    'title' : IDL.Text,
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'employmentType' : IDL.Text,
    'company' : IDL.Text,
    'employerId' : IDL.Principal,
    'benefits' : IDL.Vec(IDL.Text),
    'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'educationLevel' : IDL.Text,
    'location' : IDL.Text,
  });
  const Application = IDL.Record({
    'status' : IDL.Text,
    'resume' : IDL.Opt(IDL.Text),
    'appliedAt' : Time,
    'applicantId' : IDL.Principal,
    'expectedSalary' : IDL.Opt(IDL.Nat),
    'jobId' : IDL.Nat32,
    'coverLetter' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func(
        [JobId, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJobPosting' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          Time,
        ],
        [JobId],
        [],
      ),
    'cvFind' : IDL.Func([], [CompiledCV], ['query']),
    'deleteJobPosting' : IDL.Func([JobId], [], []),
    'filterCandidates' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Vec(CandidateProfile)],
        ['query'],
      ),
    'getCallerCandidateProfile' : IDL.Func(
        [],
        [IDL.Opt(CandidateProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CandidateProfile)],
        ['query'],
      ),
    'getFilteredJobPostings' : IDL.Func(
        [FilterCriteria],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'getJobApplications' : IDL.Func([JobId], [IDL.Vec(Application)], ['query']),
    'getJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getUserApplications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCandidateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(ExperienceEntry),
          IDL.Vec(EducationEntry),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Nat),
          Availability,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(Certification),
          IDL.Vec(JobType),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateApplicationStatus' : IDL.Func(
        [JobId, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'updateJobPosting' : IDL.Func(
        [
          JobId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          Time,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
