/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'status' : string,
  'resume' : [] | [string],
  'appliedAt' : Time,
  'applicantId' : Principal,
  'expectedSalary' : [] | [bigint],
  'jobId' : number,
  'coverLetter' : [] | [string],
}
export interface Availability {
  'preferredStartDate' : [] | [Time],
  'isAvailable' : boolean,
  'weeklyHours' : [] | [bigint],
}
export interface CandidateProfile {
  'references' : Array<string>,
  'preferredJobTypes' : Array<JobType>,
  'userId' : Principal,
  'headline' : string,
  'hourlyRate' : [] | [bigint],
  'education' : Array<EducationEntry>,
  'email' : string,
  'experience' : Array<ExperienceEntry>,
  'availability' : Availability,
  'summary' : string,
  'portfolioLinks' : Array<string>,
  'certifications' : Array<Certification>,
  'lastName' : string,
  'skills' : Array<string>,
  'location' : string,
  'resumeUrl' : [] | [string],
  'firstName' : string,
}
export interface Certification {
  'issueDate' : Time,
  'name' : string,
  'expirationDate' : [] | [Time],
  'issuingOrganization' : string,
  'credentialId' : string,
  'credentialUrl' : string,
}
export interface CompiledCV {
  'references' : Array<Reference>,
  'education' : Array<EducationEntry>,
  'summary' : string,
  'experiences' : Array<ExperienceEntry>,
  'certifications' : Array<Certification>,
  'personalInfo' : CandidateProfile,
  'skills' : Array<string>,
}
export interface EducationEntry {
  'endDate' : [] | [Time],
  'institution' : string,
  'description' : string,
  'degree' : string,
  'fieldOfStudy' : string,
  'startDate' : Time,
}
export interface ExperienceEntry {
  'title' : string,
  'endDate' : [] | [Time],
  'description' : string,
  'company' : string,
  'location' : string,
  'startDate' : Time,
}
export interface FilterCriteria {
  'experienceLevel' : string,
  'employmentType' : string,
  'salaryRange' : { 'max' : bigint, 'min' : bigint },
  'skills' : Array<string>,
  'educationLevel' : string,
  'location' : string,
}
export type JobId = number;
export interface JobPosting {
  'id' : JobId,
  'applicationDeadline' : Time,
  'experienceLevel' : string,
  'title' : string,
  'skillsRequired' : Array<string>,
  'description' : string,
  'isActive' : boolean,
  'employmentType' : string,
  'company' : string,
  'employerId' : Principal,
  'benefits' : Array<string>,
  'salaryRange' : { 'max' : bigint, 'min' : bigint },
  'educationLevel' : string,
  'location' : string,
}
export type JobType = { 'internship' : null } |
  { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null } |
  { 'freelance' : null };
export interface Reference {
  'contactInfo' : string,
  'relationship' : string,
  'fullName' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<
    [JobId, [] | [bigint], [] | [string], [] | [string]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJobPosting' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      { 'max' : bigint, 'min' : bigint },
      Array<string>,
      string,
      string,
      Array<string>,
      boolean,
      Time,
    ],
    JobId
  >,
  'cvFind' : ActorMethod<[], CompiledCV>,
  'deleteJobPosting' : ActorMethod<[JobId], undefined>,
  'filterCandidates' : ActorMethod<
    [Array<string>, bigint],
    Array<CandidateProfile>
  >,
  'getCallerCandidateProfile' : ActorMethod<[], [] | [CandidateProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateProfile' : ActorMethod<[Principal], [] | [CandidateProfile]>,
  'getFilteredJobPostings' : ActorMethod<[FilterCriteria], Array<JobPosting>>,
  'getJobApplications' : ActorMethod<[JobId], Array<Application>>,
  'getJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getUserApplications' : ActorMethod<[Principal], Array<Application>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCandidateProfile' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      Array<ExperienceEntry>,
      Array<EducationEntry>,
      Array<string>,
      [] | [bigint],
      Availability,
      string,
      [] | [string],
      Array<Certification>,
      Array<JobType>,
      Array<string>,
    ],
    undefined
  >,
  'updateApplicationStatus' : ActorMethod<
    [JobId, Principal, string],
    undefined
  >,
  'updateJobPosting' : ActorMethod<
    [
      JobId,
      string,
      string,
      string,
      string,
      string,
      { 'max' : bigint, 'min' : bigint },
      Array<string>,
      string,
      string,
      Array<string>,
      boolean,
      Time,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
