/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Application {
    status: string;
    resume?: string;
    appliedAt: Time;
    applicantId: Principal;
    expectedSalary?: bigint;
    jobId: number;
    coverLetter?: string;
}
export type Time = bigint;
export interface Availability {
    preferredStartDate?: Time;
    isAvailable: boolean;
    weeklyHours?: bigint;
}
export interface CompiledCV {
    references: Array<Reference>;
    education: Array<EducationEntry>;
    summary: string;
    experiences: Array<ExperienceEntry>;
    certifications: Array<Certification>;
    personalInfo: CandidateProfile;
    skills: Array<string>;
}
export type JobId = number;
export interface JobPosting {
    id: JobId;
    applicationDeadline: Time;
    experienceLevel: string;
    title: string;
    skillsRequired: Array<string>;
    description: string;
    isActive: boolean;
    employmentType: string;
    company: string;
    employerId: Principal;
    benefits: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    educationLevel: string;
    location: string;
}
export interface FilterCriteria {
    experienceLevel: string;
    employmentType: string;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    skills: Array<string>;
    educationLevel: string;
    location: string;
}
export interface ExperienceEntry {
    title: string;
    endDate?: Time;
    description: string;
    company: string;
    location: string;
    startDate: Time;
}
export interface EducationEntry {
    endDate?: Time;
    institution: string;
    description: string;
    degree: string;
    fieldOfStudy: string;
    startDate: Time;
}
export interface Certification {
    issueDate: Time;
    name: string;
    expirationDate?: Time;
    issuingOrganization: string;
    credentialId: string;
    credentialUrl: string;
}
export interface CandidateProfile {
    references: Array<string>;
    preferredJobTypes: Array<JobType>;
    userId: Principal;
    headline: string;
    hourlyRate?: bigint;
    education: Array<EducationEntry>;
    email: string;
    experience: Array<ExperienceEntry>;
    availability: Availability;
    summary: string;
    portfolioLinks: Array<string>;
    certifications: Array<Certification>;
    lastName: string;
    skills: Array<string>;
    location: string;
    resumeUrl?: string;
    firstName: string;
}
export interface Reference {
    contactInfo: string;
    relationship: string;
    fullName: string;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum JobType {
    internship = "internship",
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime",
    freelance = "freelance"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    applyToJob(jobId: JobId, expectedSalary: bigint | null, coverLetter: string | null, resume: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createJobPosting(title: string, description: string, company: string, location: string, employmentType: string, salaryRange: {
        max: bigint;
        min: bigint;
    }, skillsRequired: Array<string>, experienceLevel: string, educationLevel: string, benefits: Array<string>, isActive: boolean, applicationDeadline: Time): Promise<JobId>;
    cvFind(): Promise<CompiledCV>;
    deleteJobPosting(jobId: JobId): Promise<void>;
    filterCandidates(skills: Array<string>, minExperience: bigint): Promise<Array<CandidateProfile>>;
    getCallerCandidateProfile(): Promise<CandidateProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidateProfile(userId: Principal): Promise<CandidateProfile | null>;
    getFilteredJobPostings(criteria: FilterCriteria): Promise<Array<JobPosting>>;
    getJobApplications(jobId: JobId): Promise<Array<Application>>;
    getJobPostings(): Promise<Array<JobPosting>>;
    getUserApplications(userId: Principal): Promise<Array<Application>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCandidateProfile(firstName: string, lastName: string, email: string, headline: string, summary: string, skills: Array<string>, experience: Array<ExperienceEntry>, education: Array<EducationEntry>, portfolioLinks: Array<string>, hourlyRate: bigint | null, availability: Availability, location: string, resumeUrl: string | null, certifications: Array<Certification>, preferredJobTypes: Array<JobType>, references: Array<string>): Promise<void>;
    updateApplicationStatus(jobId: JobId, applicantId: Principal, newStatus: string): Promise<void>;
    updateJobPosting(jobId: JobId, title: string, description: string, company: string, location: string, employmentType: string, salaryRange: {
        max: bigint;
        min: bigint;
    }, skillsRequired: Array<string>, experienceLevel: string, educationLevel: string, benefits: Array<string>, isActive: boolean, applicationDeadline: Time): Promise<void>;
}
import type { Application as _Application, Availability as _Availability, CandidateProfile as _CandidateProfile, Certification as _Certification, CompiledCV as _CompiledCV, EducationEntry as _EducationEntry, ExperienceEntry as _ExperienceEntry, JobType as _JobType, Reference as _Reference, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyToJob(arg0: JobId, arg1: bigint | null, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createJobPosting(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: {
        max: bigint;
        min: bigint;
    }, arg6: Array<string>, arg7: string, arg8: string, arg9: Array<string>, arg10: boolean, arg11: Time): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobPosting(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobPosting(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async cvFind(): Promise<CompiledCV> {
        if (this.processError) {
            try {
                const result = await this.actor.cvFind();
                return from_candid_CompiledCV_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cvFind();
            return from_candid_CompiledCV_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJobPosting(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobPosting(arg0);
            return result;
        }
    }
    async filterCandidates(arg0: Array<string>, arg1: bigint): Promise<Array<CandidateProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterCandidates(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterCandidates(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerCandidateProfile(): Promise<CandidateProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerCandidateProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerCandidateProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateProfile(arg0: Principal): Promise<CandidateProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredJobPostings(arg0: FilterCriteria): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredJobPostings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredJobPostings(arg0);
            return result;
        }
    }
    async getJobApplications(arg0: JobId): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplications(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplications(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPostings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPostings();
            return result;
        }
    }
    async getUserApplications(arg0: Principal): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserApplications(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserApplications(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCandidateProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: Array<ExperienceEntry>, arg7: Array<EducationEntry>, arg8: Array<string>, arg9: bigint | null, arg10: Availability, arg11: string, arg12: string | null, arg13: Array<Certification>, arg14: Array<JobType>, arg15: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCandidateProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_vec_n34(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n37(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), to_candid_Availability_n40(this._uploadFile, this._downloadFile, arg10), arg11, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg12), to_candid_vec_n42(this._uploadFile, this._downloadFile, arg13), to_candid_vec_n45(this._uploadFile, this._downloadFile, arg14), arg15);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCandidateProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_vec_n34(this._uploadFile, this._downloadFile, arg6), to_candid_vec_n37(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg9), to_candid_Availability_n40(this._uploadFile, this._downloadFile, arg10), arg11, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg12), to_candid_vec_n42(this._uploadFile, this._downloadFile, arg13), to_candid_vec_n45(this._uploadFile, this._downloadFile, arg14), arg15);
            return result;
        }
    }
    async updateApplicationStatus(arg0: JobId, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateJobPosting(arg0: JobId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: {
        max: bigint;
        min: bigint;
    }, arg7: Array<string>, arg8: string, arg9: string, arg10: Array<string>, arg11: boolean, arg12: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobPosting(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobPosting(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
}
function from_candid_Application_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Availability_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Availability): Availability {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CandidateProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandidateProfile): CandidateProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Certification_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Certification): Certification {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CompiledCV_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompiledCV): CompiledCV {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_EducationEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationEntry): EducationEntry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceEntry): ExperienceEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CandidateProfile]): CandidateProfile | null {
    return value.length === 0 ? null : from_candid_CandidateProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    endDate: [] | [_Time];
    description: string;
    company: string;
    location: string;
    startDate: _Time;
}): {
    title: string;
    endDate?: Time;
    description: string;
    company: string;
    location: string;
    startDate: Time;
} {
    return {
        title: value.title,
        endDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.endDate)),
        description: value.description,
        company: value.company,
        location: value.location,
        startDate: value.startDate
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueDate: _Time;
    name: string;
    expirationDate: [] | [_Time];
    issuingOrganization: string;
    credentialId: string;
    credentialUrl: string;
}): {
    issueDate: Time;
    name: string;
    expirationDate?: Time;
    issuingOrganization: string;
    credentialId: string;
    credentialUrl: string;
} {
    return {
        issueDate: value.issueDate,
        name: value.name,
        expirationDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.expirationDate)),
        issuingOrganization: value.issuingOrganization,
        credentialId: value.credentialId,
        credentialUrl: value.credentialUrl
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    references: Array<string>;
    preferredJobTypes: Array<_JobType>;
    userId: Principal;
    headline: string;
    hourlyRate: [] | [bigint];
    education: Array<_EducationEntry>;
    email: string;
    experience: Array<_ExperienceEntry>;
    availability: _Availability;
    summary: string;
    portfolioLinks: Array<string>;
    certifications: Array<_Certification>;
    lastName: string;
    skills: Array<string>;
    location: string;
    resumeUrl: [] | [string];
    firstName: string;
}): {
    references: Array<string>;
    preferredJobTypes: Array<JobType>;
    userId: Principal;
    headline: string;
    hourlyRate?: bigint;
    education: Array<EducationEntry>;
    email: string;
    experience: Array<ExperienceEntry>;
    availability: Availability;
    summary: string;
    portfolioLinks: Array<string>;
    certifications: Array<Certification>;
    lastName: string;
    skills: Array<string>;
    location: string;
    resumeUrl?: string;
    firstName: string;
} {
    return {
        references: value.references,
        preferredJobTypes: from_candid_vec_n19(_uploadFile, _downloadFile, value.preferredJobTypes),
        userId: value.userId,
        headline: value.headline,
        hourlyRate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.hourlyRate)),
        education: from_candid_vec_n7(_uploadFile, _downloadFile, value.education),
        email: value.email,
        experience: from_candid_vec_n11(_uploadFile, _downloadFile, value.experience),
        availability: from_candid_Availability_n23(_uploadFile, _downloadFile, value.availability),
        summary: value.summary,
        portfolioLinks: value.portfolioLinks,
        certifications: from_candid_vec_n14(_uploadFile, _downloadFile, value.certifications),
        lastName: value.lastName,
        skills: value.skills,
        location: value.location,
        resumeUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.resumeUrl)),
        firstName: value.firstName
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredStartDate: [] | [_Time];
    isAvailable: boolean;
    weeklyHours: [] | [bigint];
}): {
    preferredStartDate?: Time;
    isAvailable: boolean;
    weeklyHours?: bigint;
} {
    return {
        preferredStartDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.preferredStartDate)),
        isAvailable: value.isAvailable,
        weeklyHours: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.weeklyHours))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    resume: [] | [string];
    appliedAt: _Time;
    applicantId: Principal;
    expectedSalary: [] | [bigint];
    jobId: number;
    coverLetter: [] | [string];
}): {
    status: string;
    resume?: string;
    appliedAt: Time;
    applicantId: Principal;
    expectedSalary?: bigint;
    jobId: number;
    coverLetter?: string;
} {
    return {
        status: value.status,
        resume: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.resume)),
        appliedAt: value.appliedAt,
        applicantId: value.applicantId,
        expectedSalary: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.expectedSalary)),
        jobId: value.jobId,
        coverLetter: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.coverLetter))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    references: Array<_Reference>;
    education: Array<_EducationEntry>;
    summary: string;
    experiences: Array<_ExperienceEntry>;
    certifications: Array<_Certification>;
    personalInfo: _CandidateProfile;
    skills: Array<string>;
}): {
    references: Array<Reference>;
    education: Array<EducationEntry>;
    summary: string;
    experiences: Array<ExperienceEntry>;
    certifications: Array<Certification>;
    personalInfo: CandidateProfile;
    skills: Array<string>;
} {
    return {
        references: value.references,
        education: from_candid_vec_n7(_uploadFile, _downloadFile, value.education),
        summary: value.summary,
        experiences: from_candid_vec_n11(_uploadFile, _downloadFile, value.experiences),
        certifications: from_candid_vec_n14(_uploadFile, _downloadFile, value.certifications),
        personalInfo: from_candid_CandidateProfile_n17(_uploadFile, _downloadFile, value.personalInfo),
        skills: value.skills
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [_Time];
    institution: string;
    description: string;
    degree: string;
    fieldOfStudy: string;
    startDate: _Time;
}): {
    endDate?: Time;
    institution: string;
    description: string;
    degree: string;
    fieldOfStudy: string;
    startDate: Time;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.endDate)),
        institution: value.institution,
        description: value.description,
        degree: value.degree,
        fieldOfStudy: value.fieldOfStudy,
        startDate: value.startDate
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internship: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} | {
    freelance: null;
}): JobType {
    return "internship" in value ? JobType.internship : "contract" in value ? JobType.contract : "partTime" in value ? JobType.partTime : "fullTime" in value ? JobType.fullTime : "freelance" in value ? JobType.freelance : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExperienceEntry>): Array<ExperienceEntry> {
    return value.map((x)=>from_candid_ExperienceEntry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Certification>): Array<Certification> {
    return value.map((x)=>from_candid_Certification_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobType>): Array<JobType> {
    return value.map((x)=>from_candid_JobType_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CandidateProfile>): Array<CandidateProfile> {
    return value.map((x)=>from_candid_CandidateProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EducationEntry>): Array<EducationEntry> {
    return value.map((x)=>from_candid_EducationEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Availability_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Availability): _Availability {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Certification_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Certification): _Certification {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_EducationEntry_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationEntry): _EducationEntry {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ExperienceEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceEntry): _ExperienceEntry {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    endDate?: Time;
    description: string;
    company: string;
    location: string;
    startDate: Time;
}): {
    title: string;
    endDate: [] | [_Time];
    description: string;
    company: string;
    location: string;
    startDate: _Time;
} {
    return {
        title: value.title,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        description: value.description,
        company: value.company,
        location: value.location,
        startDate: value.startDate
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Time;
    institution: string;
    description: string;
    degree: string;
    fieldOfStudy: string;
    startDate: Time;
}): {
    endDate: [] | [_Time];
    institution: string;
    description: string;
    degree: string;
    fieldOfStudy: string;
    startDate: _Time;
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        institution: value.institution,
        description: value.description,
        degree: value.degree,
        fieldOfStudy: value.fieldOfStudy,
        startDate: value.startDate
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredStartDate?: Time;
    isAvailable: boolean;
    weeklyHours?: bigint;
}): {
    preferredStartDate: [] | [_Time];
    isAvailable: boolean;
    weeklyHours: [] | [bigint];
} {
    return {
        preferredStartDate: value.preferredStartDate ? candid_some(value.preferredStartDate) : candid_none(),
        isAvailable: value.isAvailable,
        weeklyHours: value.weeklyHours ? candid_some(value.weeklyHours) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueDate: Time;
    name: string;
    expirationDate?: Time;
    issuingOrganization: string;
    credentialId: string;
    credentialUrl: string;
}): {
    issueDate: _Time;
    name: string;
    expirationDate: [] | [_Time];
    issuingOrganization: string;
    credentialId: string;
    credentialUrl: string;
} {
    return {
        issueDate: value.issueDate,
        name: value.name,
        expirationDate: value.expirationDate ? candid_some(value.expirationDate) : candid_none(),
        issuingOrganization: value.issuingOrganization,
        credentialId: value.credentialId,
        credentialUrl: value.credentialUrl
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    internship: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} | {
    freelance: null;
} {
    return value == JobType.internship ? {
        internship: null
    } : value == JobType.contract ? {
        contract: null
    } : value == JobType.partTime ? {
        partTime: null
    } : value == JobType.fullTime ? {
        fullTime: null
    } : value == JobType.freelance ? {
        freelance: null
    } : value;
}
function to_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExperienceEntry>): Array<_ExperienceEntry> {
    return value.map((x)=>to_candid_ExperienceEntry_n35(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EducationEntry>): Array<_EducationEntry> {
    return value.map((x)=>to_candid_EducationEntry_n38(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Certification>): Array<_Certification> {
    return value.map((x)=>to_candid_Certification_n43(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<JobType>): Array<_JobType> {
    return value.map((x)=>to_candid_JobType_n46(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
